name: NixOS build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: nixos-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.host }}
    runs-on: ubuntu-latest
    timeout-minutes: 120

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        host:
          - nixlensk321
          - nixlensk322

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Connect Cachix read-only
        if: github.event_name == 'pull_request'
        uses: cachix/cachix-action@v17
        with:
          name: zumuvik

      - name: Connect Cachix read-write
        if: github.event_name != 'pull_request'
        uses: cachix/cachix-action@v17
        with:
          name: zumuvik
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Check flake, formatting and linting
        run: nix flake check --print-build-logs

      - name: Build NixOS configuration
        run: |
          nix build \
            .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel \
            --print-build-logs \
            --no-link
